# Generated by Django 4.1.7 on 2023-05-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 0, 39, 58, 34056),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
