# Generated by Django 4.1.7 on 2023-05-03 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_btfacultyinfo_alter_report_report_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="btfacultyinfo",
            name="id",
        ),
        migrations.RemoveField(
            model_name="report",
            name="fac_id",
        ),
        migrations.AddField(
            model_name="report",
            name="FacultyId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.btfacultyinfo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="btfacultyinfo",
            name="FacultyId",
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 1, 9, 14, 49172),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
