# Generated by Django 4.1.7 on 2023-05-03 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_remove_attendance_fac_id_attendance_facultyid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 1, 12, 31, 939106),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="Advisor",
        ),
    ]
