# Generated by Django 4.1.7 on 2023-05-03 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_btstudentinfo_alter_report_report_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BTCourseStructure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BYear", models.IntegerField()),
                ("BSem", models.IntegerField()),
                ("Dept", models.IntegerField()),
                ("Regulation", models.FloatField()),
                ("Category", models.CharField(max_length=10)),
                ("Type", models.CharField(max_length=10)),
                ("Creditable", models.IntegerField()),
                ("Credits", models.IntegerField()),
                ("count", models.IntegerField()),
                ("Rigid", models.BooleanField()),
            ],
            options={
                "db_table": "BTCourseStructure",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 1, 18, 58, 102647),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="btcoursestructure",
            constraint=models.UniqueConstraint(
                fields=(
                    "Category",
                    "Type",
                    "Creditable",
                    "Credits",
                    "Regulation",
                    "BYear",
                    "BSem",
                    "Dept",
                ),
                name="Unique_BTCourseStructureId",
            ),
        ),
    ]
