# Generated by Django 4.1.7 on 2023-05-03 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0009_btcoursestructure_alter_report_report_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 1, 23, 3, 192432),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="BTCourses",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SubCode", models.CharField(max_length=10)),
                ("SubName", models.CharField(max_length=255)),
                ("Credits", models.IntegerField()),
                ("OfferedBy", models.IntegerField()),
                ("lectures", models.IntegerField()),
                ("tutorials", models.IntegerField()),
                ("practicals", models.IntegerField()),
                (
                    "CourseStructure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.btcoursestructure",
                    ),
                ),
            ],
            options={
                "db_table": "BTCourses",
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="btcourses",
            constraint=models.UniqueConstraint(
                fields=("SubCode", "SubName", "CourseStructure"),
                name="BTCourses_unique_course",
            ),
        ),
    ]
