# Generated by Django 4.1.7 on 2023-05-03 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0012_btregistrationstatus_alter_report_report_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 1, 27, 5, 76449),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="BTSubjects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RegEventId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.btregistrationstatus",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.btcourses",
                    ),
                ),
            ],
            options={
                "db_table": "BTSubjects",
                "managed": True,
                "unique_together": {("course", "RegEventId")},
            },
        ),
    ]
