# Generated by Django 4.1.7 on 2023-05-03 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0013_alter_report_report_id_btsubjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 1, 29, 28, 770576),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="BTFacultyAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Section", models.CharField(default="NA", max_length=2)),
                (
                    "Faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_facultyInfo",
                        to="login.btfacultyinfo",
                    ),
                ),
                (
                    "RegEventId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.btregistrationstatus",
                    ),
                ),
                (
                    "Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.btsubjects",
                    ),
                ),
            ],
            options={
                "db_table": "BTFacultyAssignment",
                "managed": True,
                "unique_together": {("Subject", "RegEventId", "Faculty", "Section")},
            },
        ),
    ]
