# Generated by Django 4.1.7 on 2023-05-04 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0014_alter_report_report_id_btfacultyassignment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="btsubjects",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="btsubjects",
            name="RegEventId",
        ),
        migrations.RemoveField(
            model_name="btsubjects",
            name="course",
        ),
        migrations.RemoveConstraint(
            model_name="btcourses",
            name="BTCourses_unique_course",
        ),
        migrations.AlterUniqueTogether(
            name="btfacultyassignment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="btcourses",
            name="CourseStructure",
        ),
        migrations.RemoveField(
            model_name="btcourses",
            name="OfferedBy",
        ),
        migrations.RemoveField(
            model_name="btcourses",
            name="lectures",
        ),
        migrations.RemoveField(
            model_name="btcourses",
            name="practicals",
        ),
        migrations.RemoveField(
            model_name="btcourses",
            name="tutorials",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Address1",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Address2",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Cycle",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Gender",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="GuardianName",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Phone",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="Regulation",
        ),
        migrations.RemoveField(
            model_name="btstudentinfo",
            name="email",
        ),
        migrations.AddField(
            model_name="btfacultyassignment",
            name="Course",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.btcourses",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 13, 40, 59, 223268),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="btfacultyassignment",
            unique_together={("Course", "Faculty", "Section")},
        ),
        migrations.AddConstraint(
            model_name="btcourses",
            constraint=models.UniqueConstraint(
                fields=("SubCode", "SubName"), name="BTCourses_unique_course"
            ),
        ),
        migrations.DeleteModel(
            name="BTCourseStructure",
        ),
        migrations.RemoveField(
            model_name="btfacultyassignment",
            name="RegEventId",
        ),
        migrations.RemoveField(
            model_name="btfacultyassignment",
            name="Subject",
        ),
        migrations.DeleteModel(
            name="BTRegistrationStatus",
        ),
        migrations.DeleteModel(
            name="BTSubjects",
        ),
    ]
