# Generated by Django 4.1.7 on 2023-05-04 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0016_alter_report_report_id_btstudentregistrations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="RegNo",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.btstudentinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="SubCode",
            field=models.ForeignKey(
                default=111,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.btcourses",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="btstudentinfo",
            name="Section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.btfacultyassignment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 15, 5, 0, 124683),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("RegNo", "SubCode", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="stud_id",
        ),
    ]
