# Generated by Django 4.1.7 on 2023-05-04 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0017_alter_attendance_unique_together_attendance_regno_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="report",
            name="FacultyId",
        ),
        migrations.AddField(
            model_name="attendance",
            name="course_id",
            field=models.ForeignKey(
                default=101,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="fac_id",
            field=models.ForeignKey(
                default=9212105,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.faculty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="stu_id",
            field=models.ForeignKey(
                default=421149,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="fac_id",
            field=models.ForeignKey(
                default=9212105,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.faculty",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="report_id",
            field=models.CharField(
                default=datetime.datetime(2023, 5, 4, 22, 4, 29, 475910),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("stu_id", "course_id", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="FacultyId",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="RegNo",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="SubCode",
        ),
    ]
